# Generated by Django 4.2 on 2025-03-05 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='User Name')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is Premium')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('user', 'User')], default='user', max_length=20, verbose_name='Role')),
                ('groups', models.ManyToManyField(related_name='useraccount_groups', to='auth.group', verbose_name='Groups')),
                ('user_permissions', models.ManyToManyField(related_name='useraccount_permissions', to='auth.permission', verbose_name='User Permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'ordering': ('-created_at',),
                'managed': True,
            },
        ),
    ]
