export const profilesData = [
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Jose Luis Echemendia Lopez",
    userName: "@Rui-Peste03",
    history: 2,
    readingList: 1,
    followers: 10,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Juan De La Pin García",
    userName: "@PinGarcía!",
    history: 1,
    readingList: 12,
    followers: 10,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Rubén el Tarru",
    userName: "@rubencito",
    history: 0,
    readingList: 21,
    followers: 0,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Alvaro Scilia Ferrer",
    userName: "@Alvaro_99",
    history: 0,
    readingList: 11,
    followers: 10,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Abel Robaina Mata",
    userName: "@MataRábano",
    history: 2,
    readingList: 1,
    followers: 10,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Jose Francisco Bárban Arencibia",
    userName: "@Barba01",
    history: 2,
    readingList: 1,
    followers: 10,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Lolo Roberto Rodriguez Piñero",
    userName: "@Piro_00",
    history: 2,
    readingList: 1,
    followers: 10,
  },
  {
    id: 1,
    avatar: "/assets/images/avatar.jpeg",
    name: "Nataly Jimenez Niebla",
    userName: "@OsitaBB",
    history: 2,
    readingList: 1,
    followers: 10,
  },
];
